export type Product = {
  id: number;
  name: string;
  price: string;
  image: string;
  sold: number;
};

export const products: Product[] = [
  {
    id: 1,
    name: "Classic Oak Chair",
    price: "$249",
    image: "/Rectangle 24.png",
    sold: 320,
  },
  {
    id: 2,
    name: "Modern Walnut Table",
    price: "$599",
    image: "/Rectangle 24.png",
    sold: 180,
  },
  {
    id: 3,
    name: "Sleek Dining Set",
    price: "$1,299",
    image: "/Rectangle 24.png",
    sold: 720,
  },
  {
    id: 4,
    name: "Minimalist Sofa",
    price: "$899",
    image: "/Rectangle 24.png",
    sold: 410,
  },
  {
    id: 5,
    name: "Lounge Accent Chair",
    price: "$349",
    image: "/Rectangle 24.png",
    sold: 260,
  },
  {
    id: 6,
    name: "Round Coffee Table",
    price: "$199",
    image: "/Rectangle 24.png",
    sold: 140,
  },
  {
    id: 7,
    name: "Sectional Sofa",
    price: "$1,499",
    image: "/Rectangle 24.png",
    sold: 1200,
  },
  {
    id: 8,
    name: "Oak Sideboard",
    price: "$799",
    image: "/Rectangle 24.png",
    sold: 560,
  },
  {
    id: 9,
    name: "Marble Console Table",
    price: "$699",
    image: "/Rectangle 24.png",
    sold: 300,
  },
  {
    id: 10,
    name: "Reclaimed Wood Bench",
    price: "$299",
    image: "/Rectangle 24.png",
    sold: 220,
  },
  {
    id: 11,
    name: "Scandi Bookshelf",
    price: "$399",
    image: "/Rectangle 24.png",
    sold: 150,
  },
  {
    id: 12,
    name: "Outdoor Patio Set",
    price: "$1,199",
    image: "/Rectangle 24.png",
    sold: 980,
  },
  {
    id: 13,
    name: "Minimal Nightstand",
    price: "$149",
    image: "/Rectangle 24.png",
    sold: 90,
  },
  {
    id: 14,
    name: "Adjustable Bar Stool",
    price: "$129",
    image: "/Rectangle 24.png",
    sold: 110,
  },
  {
    id: 15,
    name: "Designer Floor Lamp",
    price: "$219",
    image: "/Rectangle 24.png",
    sold: 450,
  },
  {
    id: 16,
    name: "Area Rug - 8x10",
    price: "$349",
    image: "/Rectangle 24.png",
    sold: 205,
  },
];

export const types = [
  { id: "chairs", name: "Chairs", image: "/Rectangle 24.png" },
  { id: "tables", name: "Tables", image: "/Rectangle 24.png" },
  { id: "sofas", name: "Sofas", image: "/Rectangle 24.png" },
  { id: "storage", name: "Storage", image: "/Rectangle 24.png" },
];

export const sampleProductsByType: Record<string, Product[]> = {
  chairs: [
    {
      id: 101,
      name: "Classic Oak Chair",
      price: "$249",
      image: "/Rectangle 24.png",
      sold: 320,
    },
    {
      id: 102,
      name: "Lounge Accent Chair",
      price: "$349",
      image: "/Rectangle 24.png",
      sold: 260,
    },
    {
      id: 103,
      name: "Bentwood Dining Chair",
      price: "$179",
      image: "/Rectangle 24.png",
      sold: 140,
    },
    {
      id: 104,
      name: "Armchair Recliner",
      price: "$429",
      image: "/Rectangle 24.png",
      sold: 95,
    },
    {
      id: 105,
      name: "Slatback Kitchen Chair",
      price: "$129",
      image: "/Rectangle 24.png",
      sold: 60,
    },
    {
      id: 106,
      name: "Upholstered Dining Chair",
      price: "$219",
      image: "/Rectangle 24.png",
      sold: 80,
    },
    {
      id: 107,
      name: "Folding Accent Chair",
      price: "$89",
      image: "/Rectangle 24.png",
      sold: 45,
    },
    {
      id: 108,
      name: "Designer Armchair",
      price: "$499",
      image: "/Rectangle 24.png",
      sold: 150,
    },
  ],
  tables: [
    {
      id: 201,
      name: "Modern Walnut Table",
      price: "$599",
      image: "/Rectangle 24.png",
      sold: 180,
    },
    {
      id: 202,
      name: "Round Coffee Table",
      price: "$199",
      image: "/Rectangle 24.png",
      sold: 140,
    },
    {
      id: 203,
      name: "Extendable Dining Table",
      price: "$999",
      image: "/Rectangle 24.png",
      sold: 220,
    },
    {
      id: 204,
      name: "Side Table Trio",
      price: "$149",
      image: "/Rectangle 24.png",
      sold: 75,
    },
    {
      id: 205,
      name: "Industrial Console Table",
      price: "$349",
      image: "/Rectangle 24.png",
      sold: 120,
    },
    {
      id: 206,
      name: "Glass Top Dining Table",
      price: "$799",
      image: "/Rectangle 24.png",
      sold: 95,
    },
    {
      id: 207,
      name: "Nesting Side Tables",
      price: "$179",
      image: "/Rectangle 24.png",
      sold: 55,
    },
    {
      id: 208,
      name: "Farmhouse Bench Table",
      price: "$549",
      image: "/Rectangle 24.png",
      sold: 130,
    },
  ],
  sofas: [
    {
      id: 301,
      name: "Minimalist Sofa",
      price: "$899",
      image: "/Rectangle 24.png",
      sold: 410,
    },
    {
      id: 302,
      name: "Sectional Sofa",
      price: "$1,499",
      image: "/Rectangle 24.png",
      sold: 1200,
    },
    {
      id: 303,
      name: "Loveseat Two-Seater",
      price: "$699",
      image: "/Rectangle 24.png",
      sold: 200,
    },
    {
      id: 304,
      name: "Convertible Sofa Bed",
      price: "$799",
      image: "/Rectangle 24.png",
      sold: 160,
    },
    {
      id: 305,
      name: "Chesterfield Sofa",
      price: "$1,099",
      image: "/Rectangle 24.png",
      sold: 240,
    },
    {
      id: 306,
      name: "Reclining Sofa",
      price: "$1,299",
      image: "/Rectangle 24.png",
      sold: 180,
    },
    {
      id: 307,
      name: "Sectional Corner Sofa",
      price: "$1,699",
      image: "/Rectangle 24.png",
      sold: 310,
    },
    {
      id: 308,
      name: "Sofa with Chaise",
      price: "$1,199",
      image: "/Rectangle 24.png",
      sold: 270,
    },
  ],
  storage: [
    {
      id: 401,
      name: "Oak Sideboard",
      price: "$799",
      image: "/Rectangle 24.png",
      sold: 560,
    },
    {
      id: 402,
      name: "Wall Shelving",
      price: "$299",
      image: "/Rectangle 24.png",
      sold: 95,
    },
    {
      id: 403,
      name: "Four-Drawer Chest",
      price: "$449",
      image: "/Rectangle 24.png",
      sold: 130,
    },
    {
      id: 404,
      name: "Entryway Console",
      price: "$249",
      image: "/Rectangle 24.png",
      sold: 75,
    },
    {
      id: 405,
      name: "Corner Cabinet",
      price: "$379",
      image: "/Rectangle 24.png",
      sold: 60,
    },
    {
      id: 406,
      name: "Media Console",
      price: "$549",
      image: "/Rectangle 24.png",
      sold: 140,
    },
    {
      id: 407,
      name: "Storage Bench",
      price: "$229",
      image: "/Rectangle 24.png",
      sold: 85,
    },
    {
      id: 408,
      name: "Bookshelf Cabinet",
      price: "$429",
      image: "/Rectangle 24.png",
      sold: 115,
    },
  ],
};
